SELECT ALLS.PERSON_ADDR_USAGE_ID,
MIN(ALLS.EFFECTIVE_START_DATE)  as EFFECTIVE_START_DATE,
ALLS.EFFECTIVE_END_DATE,
ALLS.PERSON_ID,
ALLS.BUSINESS_GROUP_ID,
ALLS.BUSINESS_GROUP_ID1,
ALLS.ADDRESS_TYPE,
MAX(ALLS.ADDRESS_LINE_1) as ADDRESS_LINE_1,
ALLS.ADDRESS_LINE_2,
ALLS.ADDRESS_LINE_3,
ALLS.ADDRESS_LINE_4,
ALLS.BUILDING,
ALLS.FLOOR_NUMBER,
ALLS.TOWN_OR_CITY,
ALLS.REGION_1,
ALLS.REGION_2,
ALLS.REGION_3,
ALLS.COUNTRY,
ALLS.POSTAL_CODE,
ALLS.LONG_POSTAL_CODE,
ALLS.TIMEZONE_CODE,
ALLS.DERIVED_LOCALE,
ALLS.DQ_VALIDATION_LEVEL,
ALLS.FORMATTED_SINGLE_LINE_ADDRESS,
ALLS.FORMATTED_MULTI_LINE_ADDRESS,
ALLS.ATTRIBUTE_CATEGORY,
ALLS.ATTRIBUTE1,
ALLS.ATTRIBUTE2,
ALLS.ATTRIBUTE3,
ALLS.ATTRIBUTE4,
ALLS.ATTRIBUTE5,
ALLS.ATTRIBUTE6,
ALLS.ATTRIBUTE7,
ALLS.ATTRIBUTE8,
ALLS.ATTRIBUTE9,
ALLS.ATTRIBUTE10,
ALLS.ATTRIBUTE11,
ALLS.ATTRIBUTE12,
ALLS.ATTRIBUTE13,
ALLS.ATTRIBUTE14,
ALLS.ATTRIBUTE15,
ALLS.ATTRIBUTE16,
ALLS.ATTRIBUTE17,
ALLS.ATTRIBUTE18,
ALLS.ATTRIBUTE19,
ALLS.ATTRIBUTE20,
ALLS.ATTRIBUTE21,
ALLS.ATTRIBUTE22,
ALLS.ATTRIBUTE23,
ALLS.ATTRIBUTE24,
ALLS.ATTRIBUTE25,
ALLS.ATTRIBUTE26,
ALLS.ATTRIBUTE27,
ALLS.ATTRIBUTE28,
ALLS.ATTRIBUTE29,
ALLS.ATTRIBUTE30,
ALLS.ADDR_ATTRIBUTE_CATEGORY,
ALLS.ADDR_ATTRIBUTE1,
ALLS.ADDR_ATTRIBUTE2,
ALLS.ADDR_ATTRIBUTE3,
ALLS.ADDR_ATTRIBUTE4,
ALLS.ADDR_ATTRIBUTE5,
ALLS.ADDR_ATTRIBUTE6,
ALLS.ADDR_ATTRIBUTE7,
ALLS.ADDR_ATTRIBUTE8,
ALLS.ADDR_ATTRIBUTE9,
ALLS.ADDR_ATTRIBUTE10,
ALLS.ADDR_ATTRIBUTE11,
ALLS.ADDR_ATTRIBUTE12,
ALLS.ADDR_ATTRIBUTE13,
ALLS.ADDR_ATTRIBUTE14,
ALLS.ADDR_ATTRIBUTE15,
ALLS.ADDR_ATTRIBUTE16,
ALLS.ADDR_ATTRIBUTE17,
ALLS.ADDR_ATTRIBUTE18,
ALLS.ADDR_ATTRIBUTE19,
ALLS.ADDR_ATTRIBUTE20,
ALLS.ADDR_ATTRIBUTE21,
ALLS.ADDR_ATTRIBUTE22,
ALLS.ADDR_ATTRIBUTE23,
ALLS.ADDR_ATTRIBUTE24,
ALLS.ADDR_ATTRIBUTE25,
ALLS.ADDR_ATTRIBUTE26,
ALLS.ADDR_ATTRIBUTE27,
ALLS.ADDR_ATTRIBUTE28,
ALLS.ADDR_ATTRIBUTE29,
ALLS.ADDR_ATTRIBUTE30,
ALLS.ADDL_ADDRESS_ATTRIBUTE1,
ALLS.ADDL_ADDRESS_ATTRIBUTE2,
ALLS.ADDL_ADDRESS_ATTRIBUTE3,
ALLS.ADDL_ADDRESS_ATTRIBUTE4,
ALLS.ADDL_ADDRESS_ATTRIBUTE5,
ALLS.FT_ALTERNATE_REC,
ALLS.FT_ALTERNATE_KEY FROM
(
SELECT ALLS_WITH_ORDER.* FROM
(
SELECT KTG.* FROM
(
select
 concat('ADDR',CRC32(UPPER(TRIM(С.ФИО)))) as PERSON_ADDR_USAGE_ID
,DATE_FORMAT(MIN(П.`Дата`),'%Y-%m-%d') as EFFECTIVE_START_DATE
, '4712-12-31' as EFFECTIVE_END_DATE
, concat('P',CRC32(UPPER(TRIM(С.ФИО)))) as PERSON_ID
, '188772AEC11AAD11E053A647660A0CF2' as BUSINESS_GROUP_ID
, '188772AEC11AAD11E053A647660A0CF2' as BUSINESS_GROUP_ID1
, 'HOME' as ADDRESS_TYPE
, С.МестоЖительства as ADDRESS_LINE_1
, '' as ADDRESS_LINE_2
, '' as ADDRESS_LINE_3
, '' as ADDRESS_LINE_4
, '' as BUILDING
, '' as FLOOR_NUMBER
, CASE
WHEN С.`МестоЖительства` LIKE '%Актау%' THEN 'Актау' 
WHEN С.`МестоЖительства` LIKE '%Актобе%' THEN 'Актобе' 
WHEN С.`МестоЖительства` LIKE '%Алматы%' THEN 'Алматы' 
WHEN С.`МестоЖительства` LIKE '%Астана%' THEN 'Астана' 
WHEN С.`МестоЖительства` LIKE '%Атырау%' THEN 'Атырау' 
WHEN С.`МестоЖительства` LIKE '%Байконыр%' THEN 'Байконыр' 
WHEN С.`МестоЖительства` LIKE '%Караганда%' THEN 'Караганда' 
WHEN С.`МестоЖительства` LIKE '%Кокшетау%' THEN 'Кокшетау' 
WHEN С.`МестоЖительства` LIKE '%Костанай%' THEN 'Костанай' 
WHEN С.`МестоЖительства` LIKE '%Кызылорда%' THEN 'Кызылорда' 
WHEN С.`МестоЖительства` LIKE '%Павлодар%' THEN 'Павлодар' 
WHEN С.`МестоЖительства` LIKE '%Петропавловск%' THEN 'Петропавловск' 
WHEN С.`МестоЖительства` LIKE '%Талдыкорган%' THEN 'Талдыкорган' 
WHEN С.`МестоЖительства` LIKE '%Тараз%' THEN 'Тараз' 
WHEN С.`МестоЖительства` LIKE '%Уральск%' THEN 'Уральск' 
WHEN С.`МестоЖительства` LIKE '%Усть-Каменогорск%' THEN 'Усть-Каменогорск' 
WHEN С.`МестоЖительства` LIKE '%Шымкент%' THEN 'Шымкент' 
ELSE 'Алматы' END as TOWN_OR_CITY
, '' as REGION_1
, '' as REGION_2
, '' as REGION_3
, 'KZ' as COUNTRY
, ' 050051' as POSTAL_CODE
, '' as LONG_POSTAL_CODE
, '' as TIMEZONE_CODE
, '' as DERIVED_LOCALE
, '' as DQ_VALIDATION_LEVEL
, '' as FORMATTED_SINGLE_LINE_ADDRESS
, '' as FORMATTED_MULTI_LINE_ADDRESS
, '' as ATTRIBUTE_CATEGORY
, '' as ATTRIBUTE1
, '' as ATTRIBUTE2
, '' as ATTRIBUTE3
, '' as ATTRIBUTE4
, '' as ATTRIBUTE5
, '' as ATTRIBUTE6
, '' as ATTRIBUTE7
, '' as ATTRIBUTE8
, '' as ATTRIBUTE9
, '' as ATTRIBUTE10
, '' as ATTRIBUTE11
, '' as ATTRIBUTE12
, '' as ATTRIBUTE13
, '' as ATTRIBUTE14
, '' as ATTRIBUTE15
, '' as ATTRIBUTE16
, '' as ATTRIBUTE17
, '' as ATTRIBUTE18
, '' as ATTRIBUTE19
, '' as ATTRIBUTE20
, '' as ATTRIBUTE21
, '' as ATTRIBUTE22
, '' as ATTRIBUTE23
, '' as ATTRIBUTE24
, '' as ATTRIBUTE25
, '' as ATTRIBUTE26
, '' as ATTRIBUTE27
, '' as ATTRIBUTE28
, '' as ATTRIBUTE29
, '' as ATTRIBUTE30
, '' as ADDR_ATTRIBUTE_CATEGORY
, '' as ADDR_ATTRIBUTE1
, '' as ADDR_ATTRIBUTE2
, '' as ADDR_ATTRIBUTE3
, '' as ADDR_ATTRIBUTE4
, '' as ADDR_ATTRIBUTE5
, '' as ADDR_ATTRIBUTE6
, '' as ADDR_ATTRIBUTE7
, '' as ADDR_ATTRIBUTE8
, '' as ADDR_ATTRIBUTE9
, '' as ADDR_ATTRIBUTE10
, '' as ADDR_ATTRIBUTE11
, '' as ADDR_ATTRIBUTE12
, '' as ADDR_ATTRIBUTE13
, '' as ADDR_ATTRIBUTE14
, '' as ADDR_ATTRIBUTE15
, '' as ADDR_ATTRIBUTE16
, '' as ADDR_ATTRIBUTE17
, '' as ADDR_ATTRIBUTE18
, '' as ADDR_ATTRIBUTE19
, '' as ADDR_ATTRIBUTE20
, '' as ADDR_ATTRIBUTE21
, '' as ADDR_ATTRIBUTE22
, '' as ADDR_ATTRIBUTE23
, '' as ADDR_ATTRIBUTE24
, '' as ADDR_ATTRIBUTE25
, '' as ADDR_ATTRIBUTE26
, '' as ADDR_ATTRIBUTE27
, '' as ADDR_ATTRIBUTE28
, '' as ADDR_ATTRIBUTE29
, '' as ADDR_ATTRIBUTE30
, '' as ADDL_ADDRESS_ATTRIBUTE1
, '' as ADDL_ADDRESS_ATTRIBUTE2
, '' as ADDL_ADDRESS_ATTRIBUTE3
, '' as ADDL_ADDRESS_ATTRIBUTE4
, '' as ADDL_ADDRESS_ATTRIBUTE5
, 'ADDRESSES' as FT_ALTERNATE_REC
, concat('ADDR',CRC32(UPPER(TRIM(С.ФИО)))) as FT_ALTERNATE_KEY
FROM kontrotenko_ktg.`Приказы` П
JOIN kontrotenko_ktg.`Сотрудники` С
ON П.`КодСотрудника`=С.`КодСотрудника`

GROUP BY UPPER(TRIM(С.`ФИО`))

) KTG
UNION ALL
SELECT KTGA.* FROM
(
select
 concat('ADDR',CRC32(UPPER(TRIM(С.ФИО)))) as PERSON_ADDR_USAGE_ID
,DATE_FORMAT(MIN(П.`Дата`),'%Y-%m-%d') as EFFECTIVE_START_DATE
, '4712-12-31' as EFFECTIVE_END_DATE
, concat('P',CRC32(UPPER(TRIM(С.ФИО)))) as PERSON_ID
, '188772AEC11AAD11E053A647660A0CF2' as BUSINESS_GROUP_ID
, '188772AEC11AAD11E053A647660A0CF2' as BUSINESS_GROUP_ID1
, 'HOME' as ADDRESS_TYPE
, С.МестоЖительства as ADDRESS_LINE_1
, '' as ADDRESS_LINE_2
, '' as ADDRESS_LINE_3
, '' as ADDRESS_LINE_4
, '' as BUILDING
, '' as FLOOR_NUMBER
, CASE
WHEN С.`МестоЖительства` LIKE '%Актау%' THEN 'Актау' 
WHEN С.`МестоЖительства` LIKE '%Актобе%' THEN 'Актобе' 
WHEN С.`МестоЖительства` LIKE '%Алматы%' THEN 'Алматы' 
WHEN С.`МестоЖительства` LIKE '%Астана%' THEN 'Астана' 
WHEN С.`МестоЖительства` LIKE '%Атырау%' THEN 'Атырау' 
WHEN С.`МестоЖительства` LIKE '%Байконыр%' THEN 'Байконыр' 
WHEN С.`МестоЖительства` LIKE '%Караганда%' THEN 'Караганда' 
WHEN С.`МестоЖительства` LIKE '%Кокшетау%' THEN 'Кокшетау' 
WHEN С.`МестоЖительства` LIKE '%Костанай%' THEN 'Костанай' 
WHEN С.`МестоЖительства` LIKE '%Кызылорда%' THEN 'Кызылорда' 
WHEN С.`МестоЖительства` LIKE '%Павлодар%' THEN 'Павлодар' 
WHEN С.`МестоЖительства` LIKE '%Петропавловск%' THEN 'Петропавловск' 
WHEN С.`МестоЖительства` LIKE '%Талдыкорган%' THEN 'Талдыкорган' 
WHEN С.`МестоЖительства` LIKE '%Тараз%' THEN 'Тараз' 
WHEN С.`МестоЖительства` LIKE '%Уральск%' THEN 'Уральск' 
WHEN С.`МестоЖительства` LIKE '%Усть-Каменогорск%' THEN 'Усть-Каменогорск' 
WHEN С.`МестоЖительства` LIKE '%Шымкент%' THEN 'Шымкент' 
ELSE 'Алматы' END as TOWN_OR_CITY
, '' as REGION_1
, '' as REGION_2
, '' as REGION_3
, 'KZ' as COUNTRY
, ' 050051' as POSTAL_CODE
, '' as LONG_POSTAL_CODE
, '' as TIMEZONE_CODE
, '' as DERIVED_LOCALE
, '' as DQ_VALIDATION_LEVEL
, '' as FORMATTED_SINGLE_LINE_ADDRESS
, '' as FORMATTED_MULTI_LINE_ADDRESS
, '' as ATTRIBUTE_CATEGORY
, '' as ATTRIBUTE1
, '' as ATTRIBUTE2
, '' as ATTRIBUTE3
, '' as ATTRIBUTE4
, '' as ATTRIBUTE5
, '' as ATTRIBUTE6
, '' as ATTRIBUTE7
, '' as ATTRIBUTE8
, '' as ATTRIBUTE9
, '' as ATTRIBUTE10
, '' as ATTRIBUTE11
, '' as ATTRIBUTE12
, '' as ATTRIBUTE13
, '' as ATTRIBUTE14
, '' as ATTRIBUTE15
, '' as ATTRIBUTE16
, '' as ATTRIBUTE17
, '' as ATTRIBUTE18
, '' as ATTRIBUTE19
, '' as ATTRIBUTE20
, '' as ATTRIBUTE21
, '' as ATTRIBUTE22
, '' as ATTRIBUTE23
, '' as ATTRIBUTE24
, '' as ATTRIBUTE25
, '' as ATTRIBUTE26
, '' as ATTRIBUTE27
, '' as ATTRIBUTE28
, '' as ATTRIBUTE29
, '' as ATTRIBUTE30
, '' as ADDR_ATTRIBUTE_CATEGORY
, '' as ADDR_ATTRIBUTE1
, '' as ADDR_ATTRIBUTE2
, '' as ADDR_ATTRIBUTE3
, '' as ADDR_ATTRIBUTE4
, '' as ADDR_ATTRIBUTE5
, '' as ADDR_ATTRIBUTE6
, '' as ADDR_ATTRIBUTE7
, '' as ADDR_ATTRIBUTE8
, '' as ADDR_ATTRIBUTE9
, '' as ADDR_ATTRIBUTE10
, '' as ADDR_ATTRIBUTE11
, '' as ADDR_ATTRIBUTE12
, '' as ADDR_ATTRIBUTE13
, '' as ADDR_ATTRIBUTE14
, '' as ADDR_ATTRIBUTE15
, '' as ADDR_ATTRIBUTE16
, '' as ADDR_ATTRIBUTE17
, '' as ADDR_ATTRIBUTE18
, '' as ADDR_ATTRIBUTE19
, '' as ADDR_ATTRIBUTE20
, '' as ADDR_ATTRIBUTE21
, '' as ADDR_ATTRIBUTE22
, '' as ADDR_ATTRIBUTE23
, '' as ADDR_ATTRIBUTE24
, '' as ADDR_ATTRIBUTE25
, '' as ADDR_ATTRIBUTE26
, '' as ADDR_ATTRIBUTE27
, '' as ADDR_ATTRIBUTE28
, '' as ADDR_ATTRIBUTE29
, '' as ADDR_ATTRIBUTE30
, '' as ADDL_ADDRESS_ATTRIBUTE1
, '' as ADDL_ADDRESS_ATTRIBUTE2
, '' as ADDL_ADDRESS_ATTRIBUTE3
, '' as ADDL_ADDRESS_ATTRIBUTE4
, '' as ADDL_ADDRESS_ATTRIBUTE5
, 'ADDRESSES' as FT_ALTERNATE_REC
, concat('ADDR',CRC32(UPPER(TRIM(С.ФИО)))) as FT_ALTERNATE_KEY
FROM kontrotenko_ktga.`Приказы` П
JOIN kontrotenko_ktga.`Сотрудники` С
ON П.`КодСотрудника`=С.`КодСотрудника`

GROUP BY UPPER(TRIM(С.`ФИО`))
) KTGA
) ALLS_WITH_ORDER
ORDER BY ALLS_WITH_ORDER.EFFECTIVE_START_DATE
) ALLS
GROUP BY ALLS.PERSON_ID
 