SELECT '' as ACTION_OCCURRENCE_ID,
'Y' as ADDS_TO_BUDGET,
CONCAT('ASG_FTE_P',CASE WHEN П.`ГруппаПриказа`=1 THEN П.ASSIGNMENT_ID ELSE
(SELECT ПЕР.ASSIGNMENT_ID FROM prykazy ПЕР
WHERE ПЕР.ГруппаПриказа=1 AND ПЕР.PERSON_ID=П.PERSON_ID AND ПЕР.`Дата` < П.`Дата`

ORDER BY ПЕР.`Дата` DESC LIMIT 1)
END) as ASSIGN_WORK_MEASURE_ID, 
CONCAT('ASSIG',CASE WHEN П.`ГруппаПриказа`=1 THEN П.ASSIGNMENT_ID ELSE
(SELECT ПЕР.ASSIGNMENT_ID FROM prykazy ПЕР
WHERE ПЕР.ГруппаПриказа=1 AND ПЕР.PERSON_ID=П.PERSON_ID AND ПЕР.`Дата` < П.`Дата`

ORDER BY ПЕР.`Дата` DESC LIMIT 1)
END) as ASSIGNMENT_ID,
'188772AEC11AAD11E053A647660A0CF2' as BUSINESS_GROUP_ID,
DATE_FORMAT(П.`Дата`,'%Y-%m-%d') as EFFECTIVE_START_DATE,
'4712-12-31' as EFFECTIVE_END_DATE,
'FTE' as UNIT,
1 as VALUE,
'' as FT_ALTERNATE_REC,
'' as FT_ALTERNATE_KEY
FROM prykazy П 
 WHERE  П.ГруппаПриказа IN(1) 
UNION ALL
SELECT '' as ACTION_OCCURRENCE_ID,'Y' as ADDS_TO_BUDGET,
CONCAT('ASG_HEAD_P',CASE WHEN П.`ГруппаПриказа`=1 THEN П.ASSIGNMENT_ID ELSE
(SELECT ПЕР.ASSIGNMENT_ID FROM prykazy ПЕР
WHERE ПЕР.ГруппаПриказа=1 AND ПЕР.PERSON_ID=П.PERSON_ID AND ПЕР.`Дата` < П.`Дата`
 
ORDER BY ПЕР.`Дата` DESC LIMIT 1)
END) as ASSIGN_WORK_MEASURE_ID, CONCAT('ASSIG',
CASE WHEN П.`ГруппаПриказа`=1 THEN П.ASSIGNMENT_ID ELSE
(SELECT ПЕР.ASSIGNMENT_ID FROM prykazy ПЕР
WHERE ПЕР.ГруппаПриказа=1 AND ПЕР.PERSON_ID=П.PERSON_ID AND ПЕР.`Дата` < П.`Дата`
 
ORDER BY ПЕР.`Дата` DESC LIMIT 1)
END) as ASSIGNMENT_ID,'188772AEC11AAD11E053A647660A0CF2' as BUSINESS_GROUP_ID,
DATE_FORMAT(П.`Дата`,'%Y-%m-%d') as EFFECTIVE_START_DATE,'4712-12-31' as EFFECTIVE_END_DATE,
'HEAD' as UNIT,1 as VALUE,'' as FT_ALTERNATE_REC,'' as FT_ALTERNATE_KEY
FROM prykazy П 
WHERE  П.ГруппаПриказа IN(1) AND П.PERSON_ID='799919483'