SELECT CONCAT('KTGA_POS_',Д.`КодДолжности`) AS POSITION_ID,
CASE WHEN ДИ.`ДатаНач` IS NOT NULL THEN DATE_FORMAT(ДИ.`ДатаНач`,'%Y-%m-%d') ELSE '2002-05-02' END as EFFECTIVE_START_DATE,
CASE WHEN ДИ.`ДатаКон` IS NOT NULL THEN DATE_FORMAT(ДИ.`ДатаКон`,'%Y-%m-%d') ELSE '4712-12-31' END AS EFFECTIVE_END_DATE,
'1595C93AA3F5DCB2E053A747660A09BD' AS BUSINESS_UNIT_ID,
 CONCAT('KTGA_POS_',Д.`КодДолжности`) AS POSITION_CODE,
'11A3CAC8E20AB4E6E053A747660AF6EC' AS BUSINESS_GROUP_ID,
 CONCAT('KTGA_DEP_',Д.`КодПодразделения`) AS ORGANIZATION_ID,
 CONCAT('KTGA_JOB_',Ф.`КодДол`) AS JOB_ID,
'1595C93AA609DCB2E053A747660A09BD' AS LOCATION_ID,
'' AS ENTRY_GRADE_ID,
'' AS ENTRY_STEP_ID,
CASE WHEN (CASE WHEN ДИ.`Состояние` IS NOT NULL THEN ДИ.`Состояние` ELSE Д.`Состояние` END)=1 THEN 'A' ELSE 'I' END as ACTIVE_STATUS,
'' AS SUPERVISOR_ID,
'' AS SUPERVISOR_ASSIGNMENT_ID,
'' AS ACTION_OCCURRENCE_ID,
'R' AS PERMANENT_TEMPORARY_FLAG,
1 AS FTE,
'APPROVED' AS HIRING_STATUS,
'FULL_TIME' AS FULL_PART_TIME,
'W' AS FREQUENCY,
'' AS TIME_NORMAL_START,
'' AS TIME_NORMAL_FINISH,
CASE WHEN Д.`ПоШтату`<2 OR Д.`ПоШтату` IS NULL THEN 'SINGLE'
ELSE'POOLED' END AS POSITION_TYPE,
'' AS PROBATION_PERIOD_UNIT_CD,
'' AS BARGAINING_UNIT_CD,
CASE WHEN Д.`ПоШтату` IS NOT NULL THEN Д.`ПоШтату` ELSE 1 END AS MAX_PERSONS,
'40' AS WORKING_HOURS,
'' AS OVERLAP_ALLOWED,
'N' AS SEASONAL_FLAG,
'' AS PROBATION_PERIOD,
'' AS SEASONAL_END_DATE,
'' AS SECURITY_CLEARANCE,
'' AS SEASONAL_START_DATE,
'' AS ATTRIBUTE_CATEGORY,
 CONCAT(Д.`Наименование`,' ',П.`Наименование`) AS NAME,
'POSITION_DATA' AS FT_ALTERNATE_REC,
 CONCAT('KTGA_POS_',Д.`КодДолжности`) AS FT_ALTERNATE_KEY
FROM `Должности` Д
JOIN `Подразделения` П ON Д.`КодПодразделения`=П.`КодПодразделения`
JOIN (
SELECT MAX(Ж.`КодДолжности`) AS `КодДол`, Ж.`Наименование`
FROM `Должности` Ж
GROUP BY Ж.`Наименование`) Ф
ON Д.`Наименование`=Ф.`Наименование`
LEFT JOIN `ДолжностиИстория` ДИ
ON Д.`КодДолжности`=ДИ.`КодДолжности` 
